services:
  blogs-app-db:
    container_name: blogs-app-db
    image: postgres:18.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  sonar:
    container_name: sonar
    image: sonarqube:community
    restart: unless-stopped
    ports:
      - "9000:9000"
    networks:
      - default
    volumes:
      - sonar_data:/opt/sonarqube/data

  blogs-app-spring:
    container_name: blogs-app-spring
    build:
      context: ../../
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://blogs-app-db:5432/${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - blogs-app-db
    networks:
      - default

volumes:
  postgres_data:
  sonar_data:

networks:
  default: